"""
Layer 7 — PR Publisher.
Takes a validated Implementation → creates a GitHub branch, commits changes, opens PR.
"""
from __future__ import annotations

import os
import textwrap
from pathlib import Path
import structlog

from layer4_planner.file_reader import get_repo_path
from layer45_agent.implementation import Implementation
from layer7_publisher.models.pr_result import PRResult
from layer7_publisher import git_ops, github_api

log = structlog.get_logger(__name__)

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")


def _detect_pr_template(repo_root: Path) -> str | None:
    """Find and read the repo's PR template if it exists."""
    template_paths = [
        ".github/PULL_REQUEST_TEMPLATE.md",
        ".github/pull_request_template.md",
        "PULL_REQUEST_TEMPLATE.md",
        "docs/pull_request_template.md",
        ".github/PULL_REQUEST_TEMPLATE/default.md",
    ]
    for tp in template_paths:
        full = repo_root / tp
        if full.exists():
            return full.read_text(encoding="utf-8", errors="replace")
    return None


def _fill_pr_template_with_llm(
    template: str, impl: Implementation, validation_summary: str
) -> str:
    """Use Haiku to intelligently fill in the repo's PR template."""
    import anthropic

    file_lines = []
    for fr in impl.file_results:
        file_lines.append(f"- `{fr.file_path}` ({fr.change_type}) — {fr.explanation[:200]}")

    prompt = f"""Fill in this PR template for the following code changes.

CRITICAL FORMAT RULES:
- Return ONLY raw markdown — NO code fences (no ``` wrapping)
- Do NOT wrap the output in a code block
- Output should render directly as GitHub markdown

## Content Rules:
- Start with a ## Summary section describing WHAT changed, WHY, and HOW
- Then include the filled checklist template
- Check (- [x]) items that are satisfied by the changes
- Leave unchecked (- [ ]) items that cannot be verified or don't apply
- Add "— N/A" after items that don't apply (e.g. no UI changes = no screenshots)
- Be honest — don't check items you can't verify
- End with a ## Validation section as a table

## PR Template:
{template}

## Changes Made:
**Summary:** {impl.plan_summary}

**Files:**
{chr(10).join(file_lines)}

**Ticket:** {impl.ticket_id}

**Validation:**
{validation_summary or "No validation run"}
"""

    try:
        client = anthropic.Anthropic()
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=2000,
            messages=[{"role": "user", "content": prompt}],
        )
        filled = response.content[0].text
        # Strip code fences if LLM wraps output in ```markdown ... ```
        if filled.strip().startswith("```"):
            lines = filled.strip().splitlines()
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            filled = "\n".join(lines)
        log.info("pr.template_filled", model="haiku", tokens=response.usage.input_tokens + response.usage.output_tokens)
    except Exception as e:
        log.warning("pr.template_fill_failed", error=str(e)[:100])
        # Fallback: just prepend summary to raw template
        filled = f"## Summary\n\n{impl.plan_summary}\n\n{template}"

    # Always append metadata
    filled += f"\n\n## Model\n\nGenerated by `{impl.model_used}`"
    filled += "\n\n---\n*Auto-generated by ticket-to-pr pipeline*"
    return filled


def _build_pr_body(impl: Implementation, validation_summary: str = "", repo_root: Path | None = None) -> str:
    """Render PR description using repo's template if available, else default format."""
    # Try to use repo's PR template
    if repo_root:
        template = _detect_pr_template(repo_root)
        if template:
            log.info("pr.using_repo_template")
            return _fill_pr_template_with_llm(template, impl, validation_summary)

    # Fallback: default format
    file_lines = []
    for fr in impl.file_results:
        icon = {"modify": "✏️", "create": "✨", "delete": "🗑️"}.get(fr.change_type, "•")
        file_lines.append(f"- {icon} `{fr.file_path}` — {fr.explanation[:300]}")

    body = textwrap.dedent(f"""
        ## Summary

        {impl.plan_summary}

        ## Files Changed

        {chr(10).join(file_lines)}

        ## Model

        Generated by `{impl.model_used}`
    """).strip()

    if validation_summary:
        body += f"\n\n## Validation\n\n```\n{validation_summary}\n```"

    body += "\n\n---\n*Auto-generated by ticket-to-pr pipeline*"
    return body


def publish(
    impl: Implementation,
    ticket_title: str,
    github_token: str | None = None,
    base_branch: str | None = None,
    validation_summary: str = "",
    draft: bool = False,
) -> PRResult:
    """
    Full publish pipeline:
    1. Determine base branch from GitHub API
    2. Create a local branch
    3. Commit all file changes
    4. Push branch to origin
    5. Open pull request
    Returns PRResult.
    """
    token = github_token or GITHUB_TOKEN
    if not token:
        return PRResult(
            ticket_id=impl.ticket_id,
            repo_id=impl.repo_id,
            branch_name="",
            pr_url="",
            pr_number=0,
            title=ticket_title,
            error="GITHUB_TOKEN not set. Set it in .env or pass --token.",
        )

    repo_root = get_repo_path(impl.repo_id)
    log.info("publisher.start", ticket_id=impl.ticket_id, repo=impl.repo_id)

    # 1 — Get base branch: prefer explicit arg > local checkout > GitHub API default
    if base_branch:
        resolved_base = base_branch
    else:
        # Use the branch that's currently checked out (matches what was indexed)
        try:
            import git as _git
            local_repo = _git.Repo(str(repo_root))
            local_branch = local_repo.active_branch.name
            # Verify this branch exists on remote
            remote_branches = [ref.remote_head for ref in local_repo.remotes.origin.refs]
            if local_branch in remote_branches:
                resolved_base = local_branch
                log.info("publisher.base_from_local", branch=resolved_base)
            else:
                resolved_base = github_api.get_default_branch(impl.repo_id, token)
                log.info("publisher.base_from_github", branch=resolved_base)
        except Exception as e:
            log.warning("publisher.default_branch_failed", error=str(e))
            try:
                resolved_base = github_api.get_default_branch(impl.repo_id, token)
            except Exception:
                resolved_base = "main"

    # 2 — Branch name
    branch_name = git_ops.make_branch_name(impl.ticket_id, ticket_title)
    log.info("publisher.branch", name=branch_name, base=resolved_base)

    try:
        git_ops.create_branch(repo_root, branch_name, base_branch=resolved_base)
    except Exception as e:
        return PRResult(
            ticket_id=impl.ticket_id,
            repo_id=impl.repo_id,
            branch_name=branch_name,
            pr_url="",
            pr_number=0,
            title=ticket_title,
            error=f"Branch creation failed: {e}",
        )

    # 3 — Commit
    modified_files = [fr.file_path for fr in impl.file_results if fr.change_type != "delete"]
    deleted_files = [fr.file_path for fr in impl.file_results if fr.change_type == "delete"]

    commit_msg = (
        f"fix({impl.ticket_id.lower()}): {ticket_title[:72]}\n\n"
        f"{impl.plan_summary[:300]}\n\n"
        f"Ticket: {impl.ticket_id}"
    )

    try:
        sha = git_ops.commit_changes(repo_root, modified_files, deleted_files, commit_msg)
        log.info("publisher.committed", sha=sha[:8])
    except Exception as e:
        return PRResult(
            ticket_id=impl.ticket_id,
            repo_id=impl.repo_id,
            branch_name=branch_name,
            pr_url="",
            pr_number=0,
            title=ticket_title,
            error=f"Commit failed: {e}",
        )

    # 4 — Push
    try:
        git_ops.push_branch(repo_root, branch_name, token, impl.repo_id)
    except Exception as e:
        return PRResult(
            ticket_id=impl.ticket_id,
            repo_id=impl.repo_id,
            branch_name=branch_name,
            pr_url="",
            pr_number=0,
            title=ticket_title,
            error=f"Push failed: {e}",
        )

    # 5 — Open PR
    pr_title = f"[{impl.ticket_id}] {ticket_title}"
    pr_body = _build_pr_body(impl, validation_summary, repo_root=Path(repo_root))

    try:
        pr = github_api.create_pull_request(
            repo_id=impl.repo_id,
            head_branch=branch_name,
            base_branch=resolved_base,
            title=pr_title,
            body=pr_body,
            token=token,
            draft=draft,
        )
    except Exception as e:
        return PRResult(
            ticket_id=impl.ticket_id,
            repo_id=impl.repo_id,
            branch_name=branch_name,
            pr_url="",
            pr_number=0,
            title=pr_title,
            files_changed=modified_files,
            error=f"PR creation failed: {e}",
        )

    result = PRResult(
        ticket_id=impl.ticket_id,
        repo_id=impl.repo_id,
        branch_name=branch_name,
        pr_url=pr["html_url"],
        pr_number=pr["number"],
        title=pr_title,
        files_changed=modified_files,
    )

    log.info("publisher.done", pr=result.pr_url, ticket_id=impl.ticket_id)
    return result
