"""
File filtering — decides which files to skip before parsing.
Fast path: path-based rules first, content checks only when needed.
"""
from pathlib import Path

from src.config import settings

# Directory names to always skip (anywhere in the path)
_SKIP_DIRS = frozenset({
    "node_modules", ".git", ".svn", "__pycache__", ".mypy_cache",
    ".ruff_cache", ".pytest_cache", "dist", "build", ".next",
    "out", "coverage", ".turbo", "vendor", "third_party",
    "venv", ".venv", "env", ".env", "site-packages",
    "migrations",  # keep migration files only if explicitly included later
})

# File name patterns to always skip
_SKIP_NAMES = frozenset({
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "poetry.lock", "Pipfile.lock", "uv.lock",
    ".DS_Store", "Thumbs.db",
})

# Extensions to always skip (binary, media, generated lock formats)
_SKIP_EXTENSIONS = frozenset({
    ".pyc", ".pyo", ".so", ".dylib", ".dll", ".exe",
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".webp",
    ".mp4", ".mp3", ".wav", ".pdf", ".zip", ".tar", ".gz",
    ".whl", ".egg", ".min.js", ".min.css",
    ".map",  # source maps — not useful to index
})

# First-5-line content markers that identify generated files
_GENERATED_MARKERS = (
    "// code generated",
    "// do not edit",
    "# generated by",
    "# this file is auto-generated",
    "// auto-generated",
    "/* eslint-disable */",  # common openapi-generator pattern
    "// @ts-nocheck",        # common in generated TS stubs
    "# auto-generated file",
    "// generated by the grpc",
    "// generated by protoc",
)

# Test file path patterns
_TEST_PATH_PATTERNS = (
    "/tests/", "/test/", "/__tests__/",
    "/spec/", "/_tests_/",
    "test_", "_test.", ".test.", ".spec.",
)


def should_skip(path: str | Path, size_bytes: int = 0) -> bool:
    """Return True if this file should be skipped entirely."""
    p = Path(path)
    parts = set(p.parts)

    # Skip if any parent directory is in the skip list
    if parts & _SKIP_DIRS:
        return True

    # Skip by file name
    if p.name in _SKIP_NAMES:
        return True

    # Skip by extension
    if p.suffix.lower() in _SKIP_EXTENSIONS:
        return True

    # Skip files that are too large
    if size_bytes > settings.max_file_size_bytes:
        return True

    return False


def is_generated(content: str) -> bool:
    """Check first 5 lines for auto-generated file markers."""
    first_block = "\n".join(content.splitlines()[:5]).lower()
    return any(marker in first_block for marker in _GENERATED_MARKERS)


def is_test_file(path: str | Path) -> bool:
    """Heuristic: is this a test file?"""
    path_str = str(path).replace("\\", "/")
    return any(pattern in path_str for pattern in _TEST_PATH_PATTERNS)
