"""[D] code_review — Review agent changes. Tuned for blueprint-constrained output.

Uses Opus but with a prompt that's aware the writer was constrained by:
- A specific plan from the explorer
- A limited tool budget (no over-engineering possible)
- File cache (writer saw exactly what it needed)

The existing L6 reviewer is designed for the unconstrained legacy agent
which sometimes over-engineers. Minion output is already minimal by design,
so the review focuses on correctness, not minimality.
"""
from __future__ import annotations

import json
import os
import subprocess

import structlog
import anthropic

from minions.engine.blueprint import NodeResult
from minions.engine.context import PipelineContext

log = structlog.get_logger(__name__)

_SMALL_DIFF_THRESHOLD_LINES = 20
_SMALL_DIFF_THRESHOLD_FILES = 1

_MINION_REVIEW_PROMPT = """\
You are reviewing code changes generated by a constrained coding agent for this ticket:

## Ticket
**{title}**
{body}

## Diff
```
{diff}
```

## Files Changed
{files_changed}

## Review Criteria

This code was generated by a blueprint-based agent with a specific plan and limited tools.
Focus on CORRECTNESS, not minimality — the agent was already constrained to minimal changes.

1. **Correctness**: Do the changes actually fix/implement what the ticket asks?
   - Does the logic match the ticket requirements?
   - Are there obvious bugs (wrong variable, missing null check, typo)?

2. **Import Safety**: Do imported symbols exist?
   - Local imports (@/lib/api, ./utils) — does the exported name exist?
   - If the diff ADDS a new export AND imports it elsewhere, that's fine.

3. **Style Match**: Do changes follow the existing code style?
   - Same quote style, indentation, naming conventions as surrounding code?

4. **No Breakage**: Could these changes break existing functionality?
   - Are existing features preserved?
   - Are existing exports still present?

## IMPORTANT
- The agent was told to edit SPECIFIC files with SPECIFIC changes. If the changes match
  what the ticket asks for, APPROVE them.
- Do NOT reject changes just because you would have done it differently.
- Do NOT reject changes for adding state/handlers that the ticket explicitly requested.
- Only REJECT if there's a real bug, broken import, or the changes don't match the ticket.
- Only put files in files_to_drop if they are genuinely unrelated to the ticket.

## Response Format (JSON only)
{{
  "approved": true/false,
  "files_to_keep": ["file1.ts"],
  "files_to_drop": [],
  "feedback": "What to fix if rejected — be specific",
  "summary": "One-line summary"
}}
"""


def _count_diff_lines(impl) -> int:
    total = 0
    for fr in impl.file_results:
        old_lines = set(fr.original_content.splitlines()) if fr.original_content else set()
        new_lines = set(fr.modified_content.splitlines()) if fr.modified_content else set()
        total += len(new_lines - old_lines) + len(old_lines - new_lines)
    return total


def execute(ctx: PipelineContext) -> NodeResult:
    if not ctx.implementation or not ctx.implementation.file_results:
        ctx.review_approved = True
        return NodeResult(success=True, tokens_used=0)

    num_files = len(ctx.implementation.file_results)
    diff_lines = _count_diff_lines(ctx.implementation)

    # Skip review for small, low-risk diffs
    if num_files <= _SMALL_DIFF_THRESHOLD_FILES and diff_lines <= _SMALL_DIFF_THRESHOLD_LINES:
        log.info("review.skip_small_diff", files=num_files, diff_lines=diff_lines)
        ctx.review_approved = True
        ctx.review_feedback = f"Skipped (small diff: {diff_lines} lines in {num_files} file)"
        return NodeResult(success=True, tokens_used=0)

    # Get diff from disk
    ctx.implementation.write_to_disk(str(ctx.repo_path))
    diff = _get_diff(ctx.repo_path)

    if not diff.strip():
        ctx.review_approved = True
        return NodeResult(success=True, tokens_used=0)

    if len(diff) > 12000:
        diff = diff[:12000] + "\n... [diff truncated]"

    files_changed = [fr.file_path for fr in ctx.implementation.file_results]

    # Call Opus with minion-tuned prompt
    prompt = _MINION_REVIEW_PROMPT.format(
        title=ctx.title,
        body=ctx.body,
        diff=diff,
        files_changed=", ".join(files_changed),
    )

    try:
        from minions.engine.model_router import get_model
        complexity = ctx.intent.get("complexity", "moderate") if ctx.intent else "moderate"
        review_model = get_model("code_review", complexity)

        client = anthropic.Anthropic()
        response = client.messages.create(
            model=review_model,
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
        )

        text = response.content[0].text.strip()
        tokens = (response.usage.input_tokens or 0) + (response.usage.output_tokens or 0)
        log.info("review.response", model=review_model, tokens=tokens)

        # Parse JSON
        if "```" in text:
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
            text = text.strip()

        data = json.loads(text)

        ctx.review_approved = data.get("approved", False)
        ctx.review_feedback = data.get("feedback", "")
        ctx.review_files_to_drop = data.get("files_to_drop", [])

        # Revert dropped files
        if ctx.review_files_to_drop:
            _revert_files(ctx)

        log.info("review.done", approved=ctx.review_approved,
                 dropped=len(ctx.review_files_to_drop), diff_lines=diff_lines)

        return NodeResult(success=True, tokens_used=tokens)

    except json.JSONDecodeError as e:
        log.warning("review.parse_failed", error=str(e))
        # For minions: fail OPEN (approve) — the writer was already constrained
        ctx.review_approved = True
        ctx.review_feedback = "Review parse failed — auto-approved (blueprint-constrained output)"
        return NodeResult(success=True, tokens_used=0)

    except Exception as e:
        log.warning("review.api_failed", error=str(e))
        # For minions: fail OPEN — better to publish and let human review
        ctx.review_approved = True
        ctx.review_feedback = f"Review unavailable ({e}) — auto-approved for human review"
        return NodeResult(success=True, tokens_used=0)


def _get_diff(repo_path) -> str:
    """Get git diff including untracked files."""
    try:
        proc = subprocess.run(
            ["git", "diff"], cwd=str(repo_path),
            capture_output=True, text=True, timeout=30,
        )
        diff = proc.stdout

        if not diff:
            proc2 = subprocess.run(
                ["git", "diff", "--cached"], cwd=str(repo_path),
                capture_output=True, text=True, timeout=30,
            )
            diff = proc2.stdout

        # Include new untracked files
        proc3 = subprocess.run(
            ["git", "status", "--short"], cwd=str(repo_path),
            capture_output=True, text=True, timeout=10,
        )
        for line in proc3.stdout.splitlines():
            if line.startswith("??"):
                ufile = line[3:].strip()
                upath = repo_path / ufile
                if upath.is_file() and upath.stat().st_size < 5000:
                    content = upath.read_text(encoding="utf-8", errors="replace")
                    diff += f"\n\n--- /dev/null\n+++ b/{ufile}\n{content}"

        return diff
    except Exception:
        return ""


def _revert_files(ctx: PipelineContext):
    """Revert files the reviewer flagged as unnecessary."""
    for fpath in ctx.review_files_to_drop:
        abs_path = ctx.repo_path / fpath
        if not abs_path.exists():
            continue

        proc = subprocess.run(
            ["git", "status", "--porcelain", fpath],
            cwd=str(ctx.repo_path), capture_output=True, text=True,
        )
        status = proc.stdout.strip()
        if status.startswith("??"):
            abs_path.unlink()
            log.info("review.deleted", file=fpath)
        elif status.startswith((" M", "M")):
            subprocess.run(
                ["git", "checkout", "--", fpath],
                cwd=str(ctx.repo_path), capture_output=True,
            )
            log.info("review.reverted", file=fpath)

    # Update implementation to remove dropped files
    ctx.implementation.file_results = [
        fr for fr in ctx.implementation.file_results
        if fr.file_path not in ctx.review_files_to_drop
    ]
    for fp in ctx.review_files_to_drop:
        ctx.modified_files.pop(fp, None)
